### ISSUE TITLE
A garland of 8 LEDs.

### ISSUE THREAD

**Issue by wolk2608** [Krutov777/stm32_garland#1]
**EN:**
A garland of 8 LEDs.
Realize the movement of the light to the left, to the right at a given speed (switching lines alternately), two lights. To smoothly ignite and extinguish the LEDs, use a PWM signal. Set the speed and direction of movement using Keypad 4x4. Which buttons to use, and what functions to give to decide on your own. Optionally, adjust the output speed and direction of movement on the LCD 320x240.

<br/><br/>

**RU:**
Гирлянда из 8-ми светодиодов.
Реализовать движение огонька влево, вправо с заданной скоростью (переключение линий поочередно), двух огней. Для плавного зажигания и потухания светодиодов использовать ШИМ сигнал. Скорость и направление движения задавать, используя Keypad 4x4. Какие кнопки использовать, и какими функциями наделить решить самостоятельно. По желанию, настроить вывод скорости и направления движения на LCD 320x240.

**Comment by Krutov777** [comment]
solved
